# Generated by Django 6.1 on 2026-09-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='khasra_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='kisan_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Govt. Verified'), ('rejected', 'Verification Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kisan_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kisan_verified_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='land_size_acres',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='pm_kisan_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='tehsil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='village_lgd_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
