# Generated by Django 6.1 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_khasra_number_user_kisan_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', help_text='Account holder name', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='Farmer bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='', help_text='Bank IFSC code', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_upi_id',
            field=models.CharField(blank=True, default='', help_text='Farmer UPI VPA for direct settlement (e.g. kisan@upi)', max_length=100),
        ),
    ]
