services:
  - type: web
    name: farmlink-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py migrate"
    startCommand: "cd backend && gunicorn farmlink.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DATA_GOV_IN_API_KEY
        value: "579b464db66ec23bdd000001154c67779ae44f07596666938a696d0c"
