# Generated by Django 6.1 on 2026-08-30 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.FloatField(help_text='Quantity in kg')),
                ('agreed_price', models.FloatField(help_text='Agreed price per kg in INR')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('settlement_ready', 'Settlement Ready'), ('settled', 'Settled'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], default='reserved', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('delivery_window_start', models.DateTimeField(blank=True, null=True)),
                ('delivery_window_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lots.lot')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
