# Generated by Django 6.1 on 2026-08-30 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('settlement_ready', 'Settlement Ready'), ('settled', 'Settled'), ('exception', 'Exception'), ('cancelled', 'Cancelled'), ('note', 'Note')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, help_text='Photo evidence URL')),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'db_table': 'fulfillment_events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.FloatField(help_text='Total amount (qty × price)')),
                ('logistics_fee', models.FloatField(help_text='Logistics deduction')),
                ('platform_fee', models.FloatField(help_text='Platform deduction')),
                ('net_farmer_amount', models.FloatField(help_text='Amount due to farmer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Release'), ('settled', 'Settled'), ('disputed', 'Disputed')], default='pending', max_length=15)),
                ('settlement_reference', models.CharField(blank=True, help_text='Simulated transaction reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='orders.order')),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
    ]
