# Generated by Django 6.1 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='payout_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('escrow_held', 'Escrow Held'), ('disbursed', 'Disbursed to Farmer'), ('failed', 'Payout Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settlement',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settlement',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settlement_reference',
            field=models.CharField(blank=True, help_text='Transaction reference', max_length=100),
        ),
    ]
