# Generated by Django 6.1 on 2026-08-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=20)),
                ('market', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('modal_price', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('source', models.CharField(default='seed', max_length=50)),
            ],
            options={
                'db_table': 'market_prices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=20)),
                ('market_cluster', models.CharField(default='Lucknow', max_length=100)),
                ('forecast_date', models.DateField()),
                ('price_low', models.FloatField(help_text='Low estimate in INR/kg')),
                ('price_base', models.FloatField(help_text='Base estimate in INR/kg')),
                ('price_high', models.FloatField(help_text='High estimate in INR/kg')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('source_version', models.CharField(default='seed-v1', help_text='Version of the data/model used', max_length=50)),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation of the forecast inputs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('commodity', 'market_cluster', 'forecast_date', 'source_version')},
            },
        ),
    ]
