# Generated by Django 6.1 on 2026-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(db_index=True, max_length=20)),
                ('market_cluster', models.CharField(default='Lucknow', max_length=100)),
                ('forecast_date', models.DateField(db_index=True)),
                ('horizon_days', models.IntegerField(default=1, help_text='How many days ahead this prediction was made')),
                ('predicted_price', models.FloatField()),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('absolute_error', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='ensemble-v5', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prediction_accuracy',
                'ordering': ['-forecast_date'],
                'unique_together': {('commodity', 'market_cluster', 'forecast_date', 'horizon_days', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Lucknow', max_length=50)),
                ('date', models.DateField()),
                ('temperature_c', models.FloatField(null=True)),
                ('humidity_pct', models.FloatField(null=True)),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('condition', models.CharField(default='Clear', max_length=50)),
                ('wind_speed_kmh', models.FloatField(default=0.0)),
                ('raw_json', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_cache',
                'unique_together': {('location', 'date')},
            },
        ),
    ]
