# Generated by Django 6.1 on 2026-08-30 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('district', models.CharField(default='Lucknow', max_length=200)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('tomato', 'Tomato'), ('onion', 'Onion'), ('potato', 'Potato')], max_length=20)),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy')], max_length=5)),
                ('available_qty', models.FloatField(help_text='Available quantity in kg')),
                ('reserved_qty', models.FloatField(default=0, help_text='Reserved quantity in kg')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal')], default='kg', max_length=10)),
                ('asking_price', models.FloatField(help_text='Price per kg in INR')),
                ('harvest_at', models.DateField(help_text='Harvest or ready date')),
                ('pickup_window_start', models.DateTimeField(help_text='Earliest pickup time')),
                ('pickup_window_end', models.DateTimeField(help_text='Latest pickup time')),
                ('quality_notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('partially_reserved', 'Partially Reserved'), ('fully_reserved', 'Fully Reserved'), ('exhausted', 'Exhausted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lots', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='lots.farm')),
            ],
            options={
                'db_table': 'lots',
                'ordering': ['-created_at'],
            },
        ),
    ]
