# Generated by Django 6.1 on 2026-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='commodity',
            field=models.CharField(choices=[('tomato', 'Tomato (Tamatar)'), ('onion', 'Onion (Pyaaz)'), ('potato', 'Potato (Aaloo)'), ('mango', 'Mango (Malihabadi Dussehri)'), ('chilli', 'Green Chilli (Hari Mirch)'), ('garlic', 'Garlic (Lahsun)'), ('ginger', 'Ginger (Adrak)'), ('spinach', 'Spinach (Palak)'), ('cauliflower', 'Cauliflower (Gobhi)'), ('wheat', 'Wheat (Gehu)')], max_length=20),
        ),
    ]
